### ISSUE TITLE
Static routes (without params)

### ISSUE THREAD

**Issue by Gurpartap** [skyline75489/SwiftRouter#3]
I'd like to have a few standalone routes. e.g. `/settings`, `/featured`, etc.

I've got something like this:

```
let router = Router.sharedInstance
router.map("/settings", controllerClass: SettingsViewController.self)
let settingsViewController = router.matchController("/settings") as? SettingsViewController
```
##### Expected result:

`settingsViewController` should contain an instance of SettingsViewController (mapped from `/settings` route).
##### Actual result:

`settingsViewController` is nil.

**Comment by skyline75489** [comment]
I'd really like to fix this. However currently I don't have an iOS develop environment(No Mac, I mean). I 'd really appreciate it if someone can help me with this.
